dubbo:
  application:
    name: dubbo_consumer_admin

  registry:
    address:  47.107.103.217:2181
    protocol: zookeeper

  protocol:
    name: dubbo
    port: 20880
  
  consumer:
    check: false