dubbo:
  application:
    name: dubbo_provider_admin

  registry:
    address:  47.107.103.217:2181
    protocol: zookeeper

  protocol:
    name: dubbo
    port: 20880

mybatis:
  type-aliases-package: com.music.review.domain
  mapper-locations: classpath:mapper/*.xml
    
spring:
  datasource:
    username: root
    password: uAiqwVwjJ8-i
    url: jdbc:mysql://47.107.103.217:3306/music_review?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
